### ISSUE TITLE
License information

### ISSUE THREAD

**Issue by TomekTrzeciak** [metocean/cf-json#23]
This project looks interesting. Is it open source? What are the license terms?

**Comment by aportagain** [comment]
Hi @TomekTrzeciak , thanks for you interest! Yes, we decided to make this free and open-source a while back, it's just been on the back burner for a while, never got around to sorting out the details... like choosing a licence :) I'll try to get this sorted within the next week. Very likely to be a permissive one, maybe Apache-2.0.

**Comment by aportagain** [comment]
Happy to confirm that we have now released under Apache-2.0 :) See https://github.com/metocean/cf-json/blob/master/README.md#license and https://github.com/metocean/cf-json/blob/master/LICENSE .
